export const DOCUMENT_REPOSITORY = Symbol("DOCUMENT_REPOSITORY");
export const DOCUMENT_LINK_REPOSITORY = Symbol("DOCUMENT_LINK_REPOSITORY");
export const DOCUMENT_DERIVATIVE_REPOSITORY = Symbol("DOCUMENT_DERIVATIVE_REPOSITORY");
export const STORAGE_ADAPTER = Symbol("STORAGE_ADAPTER");
export const DOCUMENT_RENDERER = Symbol("DOCUMENT_RENDERER");
